### ISSUE TITLE
Figure out process for updating/uploading the sitemap.xml.gz

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1192]
Prior art:

- https://github.com/crimethinc/website/issues/123
- https://github.com/crimethinc/website/issues/925
- https://github.com/crimethinc/website/issues/502

`https://crimethinc.com/sitemap.xml.gz` 404s

I'm not sure if we ever actually had the sitemap up on the production site. We might've been waiting until we could figure out a way to not manually run a script and/or have to commit the .xml.gz to source control.

It would be amazing if someone could figure out how to do this at all and even better would be how to automate it with Heroku et al.

**Comment by just1602** [comment]
@veganstraightedge, I was about to close this issue since all the previous parts are done. I try to generate the sitemap.xml.gz locally, it works, and I can download the file when I hit `localhost:3000/sitemap.xml.gz`, but when I hit `crimethinc.com/sitemap.xml.gz` I get a 404. Can you validate that `sitemap:refresh` is correctly execute when we deploy the app?

**Comment by veganstraightedge** [comment]
@just1602 @ghost thank you both for your discussion on this issue!

Sorry that I was pretty absent from that discussion.

These [two issues](https://github.com/crimethinc/website/issues/3780) helped inform my work on this PR:

- https://github.com/crimethinc/website/pull/4060

**Comment by veganstraightedge** [comment]
✅ https://crimethinc.com/sitemap.xml
