### ISSUE TITLE
Add pagination to tools

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1752]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/4361/91648433-80da5e80-ea1c-11ea-943d-b52efa4bceca.png">

Because the images are being loaded via Active Storage, they count as requests on the same domain. And because there are sooo many posters, some of the image requests are erroring with 429 TOO MANY REQUESTS.

https://httpstatuses.com/429

***

Changing the rate limit rack-attack rules could work, but I think this page has grown way too long and should be paginated anyhow. Stickers and Logos all being on one page still works because they're are not that many, but Posters (and Zines) needs it. So let's pick a per page threshold above `Sticker.count`.

**Comment by just1602** [comment]
I'm on this one, but our problem is we sort the `@featured_tools` and `@tools` from the active record relation using map, but since the gem we use for pagination use the rails models/relations to work, is it ok if y refactor the method to use relation method and than be able to use the link_to_next_page helper function?

**Comment by veganstraightedge** [comment]
Sounds like a great plan! Thanks @just1602
