### ISSUE TITLE
Collect all blog post comments from old site

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#192]
- [x] Export comments from Wordpress
- [ ] Build Comment CRUD in new site
- [ ] Build keep/delete comments admin
- [ ] if article.comments? show them in Article footer

**Comment by veganstraightedge** [comment]
The comments are the in the Wordpress export files in `/db/seeds`

**Comment by just1602** [comment]
I'd be interest in that issue, but I've some questions :

* Do we still want a comments system since the raise of the alt-right and all the trolls that come with it?
* If we want it, do we want pre or post validation?
* Pages with a lot of images are already long to load, do we want to add comments to this or we want to load them asynchronously with ajax?
* To import the comments, we need to add the code to parse the html/php files with the `articles.rb` file in `/db/seeds` ?
* Since we're on our way to redesign the site, should we only do the backend and importation part and display the comments in the next design release?

**Comment by veganstraightedge** [comment]
@just1602 

> Do we still want a comments system since the raise of the alt-right and all the trolls that come with it?

No. To clarify, we are not going to have a comments system again.

> If we want it, do we want pre or post validation?

N/A

> Pages with a lot of images are already long to load, do we want to add comments to this or we want to load them asynchronously with ajax?

N/A

> To import the comments, we need to add the code to parse the html/php files with the articles.rb file in /db/seeds ?

> Since we're on our way to redesign the site, should we only do the backend and importation part and display the comments in the next design release?

Correct. 

This issue is about excavating the old comments, so that admins can look through them and keep some. 

The good comments that are worth keeping will be copy / pasted into the bottom of their article.

**Comment by just1602** [comment]
Ok, but we could also simply extract comment to a file where they would be associated with the article / text title they are linked to and it'd avoid building an admin section that would be delete after a couple of weeks, tho ?

**Comment by veganstraightedge** [comment]
That's not a bad idea. How about this?

- [ ] comment_id
- [ ] A CSV file with the fields:
- [ ] author
- [ ] author_email
- [ ] author_url
- [ ] date_gmt
- [ ] content

***

- [ ] Strip `<![CDATA[` and `]]>` out of all saved fields

***

- [ ] article ID
- [ ] article URL
- [ ] article title : subtitle

***

- [ ] an empty column called "Keep?"

**Comment by veganstraightedge** [comment]
I was able to run the script locally and it worked great.

I collected the comments into a spreadsheet for the content folks to sort though.

Thank you so much for doing this one, @just1602! 

There's no need to merge this branch / pr though. So I'm deleting / closing it now.
