### ISSUE TITLE
Photos broken at https://crimethinc.com/2016

### ISSUE THREAD

**Issue by biofilo** [crimethinc/website#277]
When I go to https://crimethinc.com/2016 many of the images don't display properly on the left side.

**Comment by astronaut-wannabe** [comment]
just to add to @biofilo's comment.

The issue seems to be something wrong in cloudfront.

The error I see is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>E731D47286809078</RequestId>
  <HostId>Ld98r01ITkVd4V//PwMV6KoD1G+BYRzVeML5tVc944uq5IATjTUrcVevX9DiWi5woWW7SRFWS7g=</HostId>
</Error>
```

I don't see any difference between the requests that `200` and the requests that `403`
![screen shot 2017-02-02 at 4 33 02 pm](https://cloud.githubusercontent.com/assets/13190980/22574707/6324a276-e965-11e6-9a21-6292f3afc871.png)

**Comment by veganstraightedge** [comment]
I'm on it.

**Comment by veganstraightedge** [comment]
Fixed.
