### ISSUE TITLE
Investigate higher response times lately

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#299]
![screen shot 2017-02-15 at 11 39 41 am](https://cloud.githubusercontent.com/assets/4361/22992107/83ecbb70-f373-11e6-9a38-47f525d469d3.png)

We've been up above 1000 ms quite a bit. It'd be nice if we figure out what's caused that and how to bring it back down.

**Comment by astronaut-wannabe** [comment]
here's to hoping that it is just increased numbers of visitors dragging the averages up 🤞

**Comment by bookis** [comment]
So the problem is really only with `/feed`, it's about 5x slower than the next slowest page (`/`). The real time suck is literally rendering that much xml. So the easy thing to do is to render fewer articles. I've changed it from 25 to 10, if that is acceptable, then it will speed up. I've also done a couple _tiny_ optimizations (if nothing else, they clean up the logs from fewer SQL statements)

**Comment by bookis** [comment]
There are some other things we could do to speed it up (caching, optimization of generation). Caching would help the most, but you know, there can be pitfalls, although this one is probably pretty simple.

**Comment by veganstraightedge** [comment]
Let's move caching to its own issue, @bookis.

**Comment by veganstraightedge** [comment]
Actually there's an issue for this already 
#196
