### ISSUE TITLE
Unpublished article are displayed in the RSS feed

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#3528]
I have this article in my RSS feed : https://crimethinc.com/2023/09/11/introducing-ink-lite-for-zine-printing-for-when-you-need-to-make-a-little-toner-go-a-long-way

When I open it, I've this banner : 

![image](https://github.com/crimethinc/website/assets/427123/74046391-db9b-4fab-863f-e47f3d9d792c)

**Comment by bensheldon** [comment]
👋🏻 I took a look at this and I think the article may have been published and then moved back into draft mode, which is why it continued to show up in your RSS reader which had cached the old feed entry in which it was present.

I'm hypothesizing that because the feed (https://crimethinc.com/feed, linked in the footer) routes to Articles#index, which contains this scope:

https://github.com/crimethinc/website/blob/9a54e654cedf8c575a3ce266cd263555dadd21d8/app/controllers/articles_controller.rb#L5-L6

...and that includes a published scope:

https://github.com/crimethinc/website/blob/9a54e654cedf8c575a3ce266cd263555dadd21d8/app/models/concerns/featureable.rb#L10-L17

I verified locally that updating `Article.first.update(publication_status: 0)` does remove the article from the feed.

**Comment by just1602** [comment]
Oh nice ! :tada: 

This was the first time it happens, and I didn't have the time to investigate when it occurred. I'll close the issue, since it never happened again, and I'll reopen the issue if necessary.

Thanks for the investigation. :black_heart:
