### ISSUE TITLE
Improve list CSS

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#504]
![crimethinc com 2009 05 05 accounts](https://user-images.githubusercontent.com/4361/31792382-af671dda-b4d0-11e7-883f-96e3b25aa7d1.png)

**Comment by gesa** [comment]
@veganstraightedge The problem here is that "Black Bloc at the DNC, August 25, 2008" is an anchor inside an li, and all the other text is an anchor inside a paragraph inside an li. that's really hard to plan for. i recommend changing the code in the page over changing css in this case.

**Comment by veganstraightedge** [comment]
That `p` tag was a result of a different Markdown parsing bug which was fixed just now by https://github.com/crimethinc/website/commit/7c8a78a00e08ac9ae7dbc88a9a677f32a401a571

The unpleasant spacing is still present even when the `p` tag is gone.

See: https://crimethinc.com/2009/05/05/accounts

**Comment by gesa** [comment]
My point was about margin collapsing depending on whether you were using raw text, anchors, or paragraphs, or both. Lists look wonky due to the `margin-top` added in 9f08cdc. They look much better on accounts when that's changed into a `margin-bottom`, but i want to understand why the top margin was added in the first place to know where else it's gonna change.

**Comment by veganstraightedge** [comment]
I don't remember why the `margin-top` was added instead of `bottom` in particular. 

That commit was to make the lists look more like lists, especially on podcast pages.

https://crimethinc.com/podcast/58

**Comment by veganstraightedge** [comment]
<img width="743" alt="screen shot 2017-11-18 at 12 21 29 am" src="https://user-images.githubusercontent.com/4361/32978400-773e39d8-cbf6-11e7-8b58-14c3d770aa4e.png">

Much better! 🌟⭐️🌟⭐️
