### ISSUE TITLE
Fix release in Procfile

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#7]
https://github.com/CrimethIncDotCom/magazine/commit/56e052b3334c4f7f896a18843505cff323d14dc1

**Comment by bookis** [comment]
Use `heroku local` instead of `foreman start`, the only obvious difference in the commands is that `heroku local` ignores the `release` line!

Other than that, you could fix this locally by adding `&& tail -f /dev/null` just to make the `release` task run forever, but in prod this would create an extra running dyno.

Another option is to create a `Procfile.dev` without the `release` line, the start with `foreman start -f Procfile.dev`

But `heroku local` is the right thing.
